#!/usr/bin/env bash
#
# build-dist.sh — build the distribution zips, reading each skill's .distignore as the
# SINGLE SOURCE of exclusions (collapses the old dual source where CLAUDE.md's
# inline `-x` flags and the .distignore files had to be hand-synced). Also regenerates
# dist/MANIFEST.json (skill→version→sha256, so what's uploaded to the claude.ai
# org is verifiable).
#
# Exclusions per skill = baseline (*.DS_Store, the .distignore itself) + every non-comment
# line in that skill's .distignore. A trailing-slash line is treated as a directory.
# Safety net: lint-platform.sh check 2 scans the built zips for internal-only leaks.
#
# Usage:
#   ./build-dist.sh                 # rebuild ALL skill zips + regenerate the manifest
#   ./build-dist.sh <skill>         # rebuild ONE skill zip + regenerate the manifest
#   ./build-dist.sh --manifest-only # just regenerate dist/MANIFEST.json from existing zips

set -uo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$ROOT/skills"
DIST_DIR="$ROOT/dist"
command -v jq >/dev/null || { echo "build-dist needs jq" >&2; exit 2; }
# shellcheck source=lib/internal-convention.sh
. "$ROOT/lib/internal-convention.sh"   # INTERNAL_RE — defensive internal-content exclusion
SHA() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'; else shasum -a 256 "$1" | awk '{print $1}'; fi; }

MANIFEST_ONLY=0
ONLY_SKILL=""
BUILD_FAILS=0
for a in "$@"; do
  case "$a" in
    --manifest-only) MANIFEST_ONLY=1 ;;
    -*) echo "unknown flag: $a" >&2; exit 2 ;;
    *) ONLY_SKILL="$a" ;;
  esac
done

build_one() {
  local skill="$1"
  local sm="$SKILLS_DIR/$skill/SKILL.md"
  [ -f "$sm" ] || { echo "skip $skill: no SKILL.md" >&2; return; }
  local version; version=$(grep -m1 '^version:' "$sm" | sed 's/^version: *//' | tr -d ' \r')
  if ! printf '%s' "$version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "ERROR $skill: frontmatter version '$version' is not MAJOR.MINOR.PATCH — fix SKILL.md" >&2
    BUILD_FAILS=$((BUILD_FAILS+1)); return 1
  fi
  local -a excl=( -x "*.DS_Store" -x "$skill/.distignore" )
  if [ -f "$SKILLS_DIR/$skill/.distignore" ]; then
    while IFS= read -r line; do
      case "$line" in
        */) excl+=( -x "$skill/${line}*" ) ;;   # directory
        *)  excl+=( -x "$skill/$line" ) ;;        # file
      esac
    done < <(grep -vE '^\s*#|^\s*$' "$SKILLS_DIR/$skill/.distignore")
  fi
  # Defensive: exclude any internal-only file even if .distignore forgot to list it (single
  # source: lib/internal-convention.sh). lint check 2 is the post-hoc net; this stops the leak
  # at build time, before the zip is ever written.
  while IFS= read -r f; do
    [ -n "$f" ] && excl+=( -x "$f" )
  done < <(cd "$SKILLS_DIR" && find "$skill" -type f 2>/dev/null | grep -E "$INTERNAL_RE")
  local tmpzip="$DIST_DIR/.tmp-${skill}.zip"
  rm -f "$tmpzip"
  if ! ( cd "$SKILLS_DIR" && zip -qr "$tmpzip" "$skill" "${excl[@]}" ); then
    echo "ERROR $skill: zip failed — old dist zip left untouched" >&2
    rm -f "$tmpzip"; BUILD_FAILS=$((BUILD_FAILS+1)); return 1
  fi
  rm -f "$DIST_DIR/${skill}-v"*-public.zip
  mv "$tmpzip" "$DIST_DIR/${skill}-v${version}-public.zip"
  echo "built ${skill}-v${version}-public.zip"
}

gen_manifest() {
  local tmp="$DIST_DIR/MANIFEST.json"
  {
    echo '{'
    echo '  "_note": "Regenerated by build-dist.sh — do not hand-edit. Verifies what is (or should be) uploaded to the claude.ai org. No timestamp, so it only changes when a zip changes.",'
    echo '  "skills": ['
    local first=1
    for z in "$DIST_DIR"/*-public.zip; do
      [ -e "$z" ] || continue
      local base; base=$(basename "$z")
      local skill="${base%-v*}"
      local version; version=$(printf '%s' "$base" | sed -E 's/^.*-v([0-9.]+)-public\.zip$/\1/')
      local sha; sha=$(SHA "$z")
      local bytes; bytes=$(wc -c < "$z" | tr -d ' ')
      [ $first -eq 1 ] && first=0 || echo ','
      printf '    {"skill": "%s", "version": "%s", "zip": "%s", "sha256": "%s", "bytes": %s}' \
        "$skill" "$version" "$base" "$sha" "$bytes"
    done
    echo
    echo '  ]'
    echo '}'
  } > "$tmp"
  jq -e . "$tmp" >/dev/null || { echo "manifest JSON invalid" >&2; exit 2; }
  echo "regenerated dist/MANIFEST.json ($(jq '.skills|length' "$tmp") skills)"
}

if [ "$MANIFEST_ONLY" -eq 1 ]; then
  gen_manifest; exit 0
fi
if [ -n "$ONLY_SKILL" ]; then
  [ -f "$SKILLS_DIR/$ONLY_SKILL/SKILL.md" ] || { echo "build-dist: no such skill: $ONLY_SKILL" >&2; exit 2; }
  build_one "$ONLY_SKILL"
else
  for d in "$SKILLS_DIR"/*/; do build_one "$(basename "$d")"; done
fi
gen_manifest
if [ "$BUILD_FAILS" -gt 0 ]; then echo "build-dist: $BUILD_FAILS skill(s) FAILED to build" >&2; exit 1; fi
